// Rodará no back-end com uma função que retornará um JSON com todos os cards e exporta-lo
let card = [
  {
    descricao:"Celular",
    valor:1500,
    parcelas:10,
    parcelasPagas:0,
    ultimoDiaPago:22,
    ultimoMesPago:0,
    vencimento:0,
    juros:0,
    historico:null
  },
  {
    descricao:"Computador",
    valor:2595,
    parcelas:6,
    parcelasPagas:6,
    ultimoDiaPago:22,
    ultimoMesPago:0,
    vencimento:0,
    juros:0.5,
    historico:null
  },
  {
    descricao:"Televisão",
    valor:2595,
    parcelas:6,
    parcelasPagas:3,
    ultimoDiaPago:null,
    ultimoMesPago:0,
    vencimento:22,
    juros:0.5,
    historico:null
  },
  {
    descricao:"Monitor",
    valor:100,
    parcelas:2,
    parcelasPagas:1,
    ultimoDiaPago:25,
    ultimoMesPago:0,
    vencimento:22,
    juros:0.5,
    historico:null
  }
]

export {card as card};